version: '3.3'
services:
  gamesquery:
      build: .
      environment:
        - GIANTBOMB_API_KEY=${GIANTBOMB_API_KEY}
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./app:/app
      ports:
        - "8000:80"
      container_name: gamesquery
