version: '3.3'
services:
  gamesquery:
      build: .
      environment:
        - GIANTBOMB_API_KEY=${GIANTBOMB_API_KEY}
      command: python manage.py runserver 0:8000
      volumes:
        - .:/code
      expose:
        - "8000"
      ports:
        - "8000:8000"
      container_name: gamesquery
